# Generated by Django 4.2 on 2025-12-16 22:40

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, verbose_name='Архивтеу себебі')),
            ],
            options={
                'verbose_name': 'Архив жазбасы',
                'verbose_name_plural': 'Архив жазбалары',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Архивтелген күні'),
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.notification_image_path, verbose_name='Сурет'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Маңызды'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('active', 'Белсенді'), ('archived', 'Архивтелген'), ('deleted', 'Жойылған')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'created_at'], name='core_notifi_status_382268_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'status'], name='core_notifi_notific_cfce42_idx'),
        ),
        migrations.AddField(
            model_name='notificationarchive',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationarchive',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_record', to='core.notification'),
        ),
    ]
