# Generated by Django 4.2 on 2025-12-16 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationarchive_notification_archive_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Қаралған уақыты')),
            ],
            options={
                'verbose_name': 'Қаралған хабарландыру',
                'verbose_name_plural': 'Қаралған хабарландырулар',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пайдаланушы', 'verbose_name_plural': 'Пайдаланушылар'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'permissions': [('can_archive', 'Хабарландыруды архивке қоюға болады'), ('can_restore', 'Хабарландыруды архивтен қалпына келтіруге болады')], 'verbose_name': 'Хабарландыру', 'verbose_name_plural': 'Хабарландырулар'},
        ),
        migrations.AlterModelOptions(
            name='notificationarchive',
            options={'ordering': ['-archived_at'], 'verbose_name': 'Архив жазбасы', 'verbose_name_plural': 'Архив жазбалары'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Тіркелген уақыты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='notification',
            name='archive_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Архивтеу себебі'),
        ),
        migrations.AddField(
            model_name='notification',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивке қойған'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_created', to=settings.AUTH_USER_MODEL, verbose_name='Құрушы'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'Жалпы хабарландыру'), ('group', 'Группаға арналған хабарландыру')], default='general', max_length=20, verbose_name='Түрі'),
        ),
        migrations.AlterField(
            model_name='notificationarchive',
            name='archived_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Архивтелген уақыты'),
        ),
        migrations.AlterField(
            model_name='notificationarchive',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_records', to=settings.AUTH_USER_MODEL, verbose_name='Архивке қойған'),
        ),
        migrations.AlterField(
            model_name='notificationarchive',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_record', to='core.notification', verbose_name='Хабарландыру'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['group', 'status'], name='core_notifi_group_i_89f61c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_important', 'status'], name='core_notifi_is_impo_32261b_idx'),
        ),
        migrations.AddField(
            model_name='notificationview',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.notification', verbose_name='Хабарландыру'),
        ),
        migrations.AddField(
            model_name='notificationview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_views', to=settings.AUTH_USER_MODEL, verbose_name='Пайдаланушы'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationview',
            unique_together={('user', 'notification')},
        ),
    ]
